import { contentImages, contentText } from "@lumisca/core/shared";
import type {
  AgentMessage,
  AssistantMessage,
  ModeMessage,
  ToolCallBlock,
  ToolResultMessage,
} from "../../types.ts";
import { ToolCall } from "../ToolCall.tsx";
import { NotificationRow } from "../NotificationRow.tsx";
import { CopyableUserMessage } from "./CopyableUserMessage.tsx";
import { MarkdownBlock } from "./MarkdownBlock.tsx";
import { modeRewindText } from "../../slashCommands.ts";
import type { UserMessageImage } from "./types.ts";

/** One message of a turn: user messages get the action row, notifications
 * are compact rows, mode messages show the short text + badge, assistant
 * messages render text + tool calls. */
export function MessageRow({
  message,
  toolResults,
  runningTools,
  onRewind,
}: {
  message: AgentMessage;
  toolResults: Map<string, ToolResultMessage>;
  runningTools: Map<string, string>;
  onRewind?: (
    timestamp: number,
    text: string,
    images: UserMessageImage[],
  ) => void;
}) {
  if (message.role === "toolResult") return null;

  // System notifications are compact one-line rows, not user messages.
  if (message.role === "notification") {
    return <NotificationRow message={message} />;
  }

  // Mode messages (generated by slash commands like /review) show the
  // short text + mode badge instead of the full prompt. The rewind action
  // restores the mode's command line (`/plan 依頼文`) for text-taking
  // modes, so a re-send re-enters the mode instead of degrading to a
  // plain message.
  if (message.role === "mode") {
    const modeMsg = message as ModeMessage;
    return (
      <CopyableUserMessage
        text={modeMsg.shortText}
        images={[]}
        timestamp={modeMsg.timestamp}
        modeLabel={modeMsg.modeLabel}
        rewindText={modeRewindText(modeMsg.modeId, modeMsg.shortText)}
        onRewind={onRewind ?? (() => {})}
      />
    );
  }

  if (message.role === "user") {
    const text = contentText(message.content);
    const imageBlocks = contentImages(message.content);
    return (
      <CopyableUserMessage
        text={text}
        images={imageBlocks}
        timestamp={message.timestamp}
        onRewind={onRewind ?? (() => {})}
      />
    );
  }

  const assistant = message as AssistantMessage;
  const text = contentText(assistant.content);
  const toolCalls = assistant.content.filter(
    (b): b is ToolCallBlock => b.type === "toolCall",
  );

  return (
    <div className="msg">
      <div className="msg-body markdown">
        {text && <MarkdownBlock text={text} />}
        {toolCalls.map((tc) => (
          <ToolCall
            key={tc.id}
            toolCall={tc}
            result={toolResults.get(tc.id)}
            running={runningTools.has(tc.id)}
          />
        ))}
      </div>
    </div>
  );
}
