/** Composite tab key: sessions are identified by (peerId, sessionId).
 * Sessions on this server (peerId "") use the bare session id.
 *
 * The peer id is escaped: it comes from the connection registry the user
 * edits, so it may contain the separator, and reading an id like `a:b`
 * naively would split it into peer `a` and session `b:<id>` — another
 * peer's session. The other half needs no escaping: session and workspace
 * ids are generated by the server (core/session/repo.ts,
 * core/workspace/repo.ts) and are always UUIDs.
 *
 * The escape touches `%` and the separator only, and is total in both
 * directions, so every id round-trips and no key can fail to parse. */
const SEPARATOR = ":";

export function tabKey(peerId: string, sessionId: string): string {
  return peerId === ""
    ? sessionId
    : `${escapePeerId(peerId)}${SEPARATOR}${sessionId}`;
}

/** Split a tab key back into (peerId, sessionId). */
export function splitTabKey(
  key: string,
): { peerId: string; sessionId: string } {
  const i = key.indexOf(SEPARATOR);
  if (i === -1) return { peerId: "", sessionId: key };
  return {
    peerId: unescapePeerId(key.slice(0, i)),
    sessionId: key.slice(i + 1),
  };
}

/** `%` → `%25` first, then `:` → `%3A`, so an id that already reads as an
 * escape sequence cannot decode into a separator. */
function escapePeerId(peerId: string): string {
  return peerId.replaceAll("%", "%25").replaceAll(SEPARATOR, "%3A");
}

function unescapePeerId(escaped: string): string {
  return escaped.replaceAll("%3A", SEPARATOR).replaceAll("%25", "%");
}
