import { join } from "node:path";
import { Hono, type MiddlewareHandler } from "hono";
import { cors } from "hono/cors";
import { upgradeWebSocket } from "hono/deno";
import { type LumiscaCore, THEME_KEY } from "@lumisca/core";
import { bundleClient } from "./bundle.ts";
import { renderAppMarkup, renderHtmlDocument } from "./render.tsx";
import { createViteDevServer, type ViteDev } from "./vite-dev.ts";
import { SourceWatcher } from "./watch.ts";
import {
  webClientEntry,
  webFaviconPath,
  webSrcDir,
  webStylesPath,
} from "./paths.ts";
import { fsRoutes } from "./routes/fs.ts";
import { workspaceRoutes } from "./routes/workspaces.ts";
import { sessionRoutes } from "./routes/sessions.ts";
import { providerRoutes } from "./routes/providers.ts";
import { settingRoutes } from "./routes/settings.ts";
import { mcpRoutes } from "./routes/mcp.ts";
import { jsonError } from "./routes/util.ts";
import type { InitialData } from "@lumisca/web/types";

export interface AppOptions {
  /** Repository root (defaults to the current working directory). */
  repoRoot?: string;
  /** Watch frontend sources; rebundle and notify clients on change. */
  watch?: boolean;
  /** When set, /api/* and /ws require this token (X-Lumisca-Token header,
   * or the `token` query parameter for browser WebSockets). Used by the
   * desktop shell so only its own spawned server instance answers. */
  token?: string;
}

/** Lazily built/loaded frontend assets (client bundle, css, favicon). */
class Assets {
  private appJs: string | null = null;
  private appJsPromise: Promise<string> | null = null;
  private buildGen = 0;
  private buildQueue: Promise<unknown> = Promise.resolve();
  private css: string | null = null;
  private favicon: Uint8Array | null = null;

  constructor(
    private readonly repoRoot: string,
    private readonly cacheDir: string,
  ) {}

  /** Packaged builds (deno compile, no repository layout) serve the
   * prebuilt assets from a JSON manifest pointed to by LUMISCA_ASSETS_FILE
   * (generated by scripts/build-desktop-assets.ts). */
  private async embedded(
    name: "app.js" | "styles.css" | "favicon.svg",
  ): Promise<string | undefined> {
    const path = Deno.env.get("LUMISCA_ASSETS_FILE");
    if (!path) return undefined;
    try {
      const manifest = JSON.parse(await Deno.readTextFile(path)) as Record<
        string,
        string
      >;
      return manifest[name];
    } catch {
      return undefined;
    }
  }

  private hasWebSources(): boolean {
    try {
      return Deno.statSync(webClientEntry(this.repoRoot)).isFile;
    } catch {
      return false;
    }
  }

  /** Drop cached artifacts so the next request rebuilds them. */
  invalidate(): void {
    this.appJs = null;
    this.appJsPromise = null;
    this.css = null;
    this.buildGen++;
  }

  /** Build once; concurrent first requests share the same build. A failed
   * build resets the cache so the next request retries, and an invalidation
   * mid-build prevents the stale result from being cached. */
  getAppJs(): Promise<string> {
    if (this.appJs !== null) return Promise.resolve(this.appJs);
    if (this.appJsPromise === null) {
      const gen = this.buildGen;
      this.appJsPromise = this.buildAppJs().then(
        (js) => {
          if (gen === this.buildGen) {
            this.appJs = js;
          } else {
            // Sources changed while this build was running; serve the
            // result once but do not cache it — the next request rebuilds.
            this.appJsPromise = null;
          }
          return js;
        },
        (error) => {
          // A failed build must not poison the cache: the next request
          // retries (in dev, invalidate() also clears it).
          this.appJsPromise = null;
          throw error;
        },
      );
    }
    return this.appJsPromise;
  }

  private buildAppJs(): Promise<string> {
    const run = async (): Promise<string> => {
      if (!this.hasWebSources()) {
        // Packaged build: serve the prebuilt bundle.
        const embedded = await this.embedded("app.js");
        if (embedded !== undefined) return embedded;
        throw new Error(
          "Frontend sources not found and no embedded assets " +
            "(set LUMISCA_ASSETS_FILE or run from the repository)",
        );
      }
      await Deno.mkdir(this.cacheDir, { recursive: true });
      const outfile = join(this.cacheDir, "app.js");
      await bundleClient({
        cwd: this.repoRoot,
        entry: webClientEntry(this.repoRoot),
        outfile,
      });
      return Deno.readTextFile(outfile);
    };
    // Serialize builds: the dev watcher can invalidate mid-build, and two
    // esbuild runs must never write the same outfile concurrently.
    const next = this.buildQueue.then(run, run);
    this.buildQueue = next.then(() => {}, () => {});
    return next;
  }

  async getCss(): Promise<string> {
    if (this.css === null) {
      if (this.hasWebSources()) {
        this.css = await Deno.readTextFile(webStylesPath(this.repoRoot));
      } else {
        const embedded = await this.embedded("styles.css");
        if (embedded === undefined) {
          throw new Error("styles.css not found and no embedded assets");
        }
        this.css = embedded;
      }
    }
    return this.css;
  }

  async getFavicon(): Promise<Uint8Array> {
    if (this.favicon === null) {
      if (this.hasWebSources()) {
        this.favicon = await Deno.readFile(webFaviconPath(this.repoRoot));
      } else {
        const embedded = await this.embedded("favicon.svg");
        if (embedded === undefined) {
          throw new Error("favicon.svg not found and no embedded assets");
        }
        this.favicon = new TextEncoder().encode(embedded);
      }
    }
    return this.favicon;
  }
}

/** Hostnames allowed to reach the server (loopback only, DNS-rebinding guard). */
const LOOPBACK_HOSTS = new Set(["127.0.0.1", "localhost", "::1"]);

function hostnameOf(host: string | undefined): string {
  if (!host) return "";
  try {
    return new URL(`http://${host}`).hostname.replace(/^\[|\]$/g, "");
  } catch {
    return "";
  }
}

/** Origins allowed to read cross-origin responses (the Tauri WebView). */
const ALLOWED_ORIGINS = new Set([
  "tauri://localhost",
  "http://tauri.localhost",
]);

function isAllowedOrigin(origin: string, host: string | undefined): boolean {
  if (ALLOWED_ORIGINS.has(origin)) return true;
  try {
    const expected = new URL(`http://${host}`);
    const actual = new URL(origin);
    if (actual.origin === expected.origin) return true;
    // `localhost` / `127.0.0.1` / `::1` are the same server but different
    // origins; allow those loopback spellings only when the port matches,
    // so a different local port can never pass the check (otherwise any
    // other local dev server could read the API cross-origin).
    return actual.protocol === expected.protocol &&
      actual.port === expected.port &&
      LOOPBACK_HOSTS.has(actual.hostname.replace(/^\[|\]$/g, "")) &&
      LOOPBACK_HOSTS.has(hostnameOf(host));
  } catch {
    return false;
  }
}

/** Cleanup hooks per app instance (dev watcher), reached via disposeServer. */
const appDisposers = new WeakMap<Hono, () => void>();
const serverDisposers = new WeakMap<
  Deno.HttpServer<Deno.NetAddr>,
  () => void
>();

function disposeApp(app: Hono): void {
  appDisposers.get(app)?.();
}

/** Create the HTTP + WebSocket application. */
export function createApp(core: LumiscaCore, options: AppOptions = {}): Hono {
  const app = new Hono();
  const repoRoot = options.repoRoot ?? Deno.cwd();
  const assets = new Assets(repoRoot, join(repoRoot, ".lumisca-cache"));
  const watch = options.watch ?? Deno.env.get("LUMISCA_DEV") === "1";

  // The server is local-only: refuse requests that do not target a loopback
  // host (blocks DNS rebinding and cross-origin browser access).
  app.use("*", async (c, next) => {
    if (!LOOPBACK_HOSTS.has(hostnameOf(c.req.header("host")))) {
      return c.text("Forbidden: only loopback access is allowed", 403);
    }
    await next();
  });

  // Optional bearer token: blocks arbitrary local processes (curl, other
  // apps) from driving the agent. The SSR page embeds the token so the
  // same-origin UI authenticates transparently.
  if (options.token) {
    const tokenGuard: MiddlewareHandler = async (c, next) => {
      const supplied = c.req.header("x-lumisca-token") ??
        c.req.query("token");
      if (supplied !== options.token) {
        return c.json(
          { error: "Unauthorized: missing or invalid token" },
          401,
        );
      }
      await next();
    };
    app.use("/api/*", tokenGuard);
    app.use("/ws", tokenGuard);
  }

  // Route handlers throw instead of catching: unify error responses here.
  app.onError((error, c) => {
    return jsonError(c, error);
  });

  // Unknown API paths answer JSON like every other error, not an empty body.
  app.notFound((c) => {
    if (c.req.path.startsWith("/api") || c.req.path === "/ws") {
      return c.json({ error: "Not found" }, 404);
    }
    return c.text("Not found", 404);
  });

  // Connected websocket clients; used to broadcast reloads in dev mode.
  const wsClients = new Set<WebSocket>();
  const reloadClients = () => {
    const message = JSON.stringify({ type: "reload" });
    for (const client of wsClients) {
      try {
        client.send(message);
      } catch {
        wsClients.delete(client);
      }
    }
  };

  // Dev mode: serve and hot-reload frontend sources through an in-process
  // Vite dev server (middleware mode). Vite's connect middleware is
  // Node-specific, so client modules are served via transformRequest below
  // and HMR reaches the browser over Vite's own websocket. If Vite cannot
  // start (deps missing, …), fall back to the esbuild bundle + full page
  // reload path.
  let watcher: SourceWatcher | null = null;
  let viteDev: ViteDev | null = null;
  let viteDevPromise: Promise<ViteDev | null> | null = null;
  const getViteDev = (): Promise<ViteDev | null> => {
    if (viteDev !== null) return Promise.resolve(viteDev);
    if (viteDevPromise === null) {
      viteDevPromise = createViteDevServer(repoRoot).then(
        (vd) => {
          viteDev = vd;
          return vd;
        },
        (error) => {
          console.error(
            "Vite dev server failed to start; falling back to esbuild " +
              "bundling with full page reloads:",
            error,
          );
          viteDevPromise = null;
          return null;
        },
      );
    }
    return viteDevPromise;
  };
  const startFallbackWatcher = () => {
    watcher = new SourceWatcher(webSrcDir(repoRoot));
    watcher.start(() => {
      assets.invalidate();
      reloadClients();
    });
  };
  if (watch) {
    getViteDev().then((vd) => {
      if (vd === null) startFallbackWatcher();
    });
  }
  appDisposers.set(app, () => {
    watcher?.stop();
    viteDev?.close();
  });

  // Dev mode: serve transformed frontend modules (/@vite/*, /@fs/*,
  // /src/*, …). Requests Vite does not own fall through to the routes.
  if (watch) {
    app.use("*", async (c, next) => {
      const vd = await getViteDev();
      if (vd === null) return next();
      try {
        const response = await vd.serveModule(c.req.raw);
        if (response === null) return next();
        return response;
      } catch (error) {
        return c.text(
          `Vite module transform failed: ${
            error instanceof Error ? error.message : String(error)
          }`,
          500,
        );
      }
    });
  }

  // The desktop shell (Tauri WebView) calls the API from another origin.
  // Only same-origin and the Tauri WebView origins may read responses.
  const corsHandler = cors({
    origin: (origin, c) =>
      isAllowedOrigin(origin, c.req.header("host")) ? origin : undefined,
    allowHeaders: ["content-type", "x-lumisca-token"],
  });
  app.use("/api/*", corsHandler);
  app.use("/ws", corsHandler);

  // Browsers send an Origin on WebSocket handshakes; CORS does not apply to
  // WS, so without this check any website could open ws://127.0.0.1:<port>/ws
  // and read every agent event. Non-browser clients (no Origin) are allowed —
  // they are already gated by the loopback-only Host check above.
  app.use("/ws", async (c, next) => {
    const origin = c.req.header("origin");
    if (
      origin !== undefined && !isAllowedOrigin(origin, c.req.header("host"))
    ) {
      return c.text("Forbidden: cross-origin WebSocket", 403);
    }
    await next();
  });

  app.get("/api/health", (c) => c.json({ ok: true }));

  // --- SSR page -------------------------------------------------------------

  /** Initial data for the app shell, shared by the SSR page and the
   * externalized /assets/initial-data.js script (inline scripts are banned
   * by the page CSP). */
  const initialData = (): InitialData => ({
    workspaces: core.listWorkspaces(),
    theme: core.getSetting(THEME_KEY) === "light" ? "light" : "dark",
  });

  const renderPage = async () => {
    // Dev mode: render from the live sources via Vite's module runner and
    // let Vite inject its HMR client into the HTML.
    const vd = watch ? await getViteDev() : null;
    if (vd !== null) {
      const markup = await vd.renderAppMarkup(initialData());
      const html = await vd.transformIndexHtml(
        "/",
        renderHtmlDocument(markup, initialData(), "", {
          dev: true,
          token: options.token,
        }),
      );
      return new Response(html, {
        headers: { "content-type": "text/html; charset=utf-8" },
      });
    }
    const [markup, css] = await Promise.all([
      renderAppMarkup(initialData()),
      assets.getCss(),
    ]);
    return new Response(renderHtmlDocument(markup, initialData(), css), {
      headers: { "content-type": "text/html; charset=utf-8" },
    });
  };

  app.get("/", renderPage);

  app.get("/assets/initial-data.js", (c) => {
    // `<` is escaped so the JSON can never close the script tag.
    const safeData = JSON.stringify(initialData()).replace(/</g, "\\u003c");
    const tokenLine = options.token
      ? `\nwindow.__LUMISCA_TOKEN__ = ${JSON.stringify(options.token)};`
      : "";
    return c.body(`window.__INITIAL_DATA__ = ${safeData};${tokenLine}`, 200, {
      "content-type": "application/javascript; charset=utf-8",
    });
  });

  app.get("/assets/app.js", async (c) => {
    try {
      const js = await assets.getAppJs();
      return c.body(js, 200, {
        "content-type": "application/javascript; charset=utf-8",
      });
    } catch (error) {
      return c.text(
        `Client bundle build failed: ${
          error instanceof Error ? error.message : String(error)
        }`,
        500,
      );
    }
  });

  app.get("/styles.css", async (c) => {
    try {
      const css = await assets.getCss();
      return c.body(css, 200, { "content-type": "text/css; charset=utf-8" });
    } catch (error) {
      return c.text(String(error), 500);
    }
  });

  app.get("/favicon.svg", async (c) => {
    try {
      const svg = await assets.getFavicon();
      return c.newResponse(svg.buffer as ArrayBuffer, 200, {
        "content-type": "image/svg+xml",
      });
    } catch {
      return c.text("not found", 404);
    }
  });

  // SPA fallback: any other page renders the app shell.
  app.get("*", (c, next) => {
    if (c.req.path.startsWith("/api") || c.req.path === "/ws") {
      return next();
    }
    // Unknown static assets (e.g. /favicon.ico) get a real 404 instead of
    // the HTML shell, so browsers and CDNs do not cache a wrong document.
    if (/\.\w+$/.test(c.req.path)) {
      return c.text("Not found", 404);
    }
    return renderPage();
  });

  // --- API routes (mounted after the SPA fallback so /api passes through) ----

  app.route("/api", fsRoutes());
  app.route("/api", workspaceRoutes(core));
  app.route("/api", mcpRoutes(core));
  app.route("/api", sessionRoutes(core));
  app.route("/api", providerRoutes(core));
  app.route("/api", settingRoutes(core));

  // --- websocket event stream ------------------------------------------------

  const ws = upgradeWebSocket(() => {
    let unsubscribe: (() => void) | undefined;
    return {
      onOpen(_evt, ws) {
        if (ws.raw) wsClients.add(ws.raw);
        unsubscribe = core.subscribe((event) => {
          ws.send(JSON.stringify(event));
        });
      },
      onClose(_evt, ws) {
        unsubscribe?.();
        if (ws.raw) wsClients.delete(ws.raw);
      },
    };
  });

  app.get("/ws", ws);

  return app;
}

/** Start the server on 127.0.0.1:port. */
export function startServer(
  core: LumiscaCore,
  port = 8000,
  options?: AppOptions,
): Deno.HttpServer<Deno.NetAddr> {
  const app = createApp(core, options);
  const server = Deno.serve({ hostname: "127.0.0.1", port }, app.fetch);
  serverDisposers.set(server, () => disposeApp(app));
  return server;
}

/** Release resources tied to a running server (e.g. the dev watcher).
 * Call before server.shutdown() when shutting down gracefully. */
export function disposeServer(server: Deno.HttpServer<Deno.NetAddr>): void {
  serverDisposers.get(server)?.();
}
