import { join } from "node:path";
import { type Context, Hono } from "hono";
import { cors } from "hono/cors";
import { upgradeWebSocket } from "hono/deno";
import {
  errorMessage,
  type LumiscaCore,
  THEME_KEY,
  type ThemeSetting,
} from "@lumisca/core";
import { bundleClient } from "./bundle.ts";
import { renderHtmlDocument } from "./render.ts";
import { webClientEntry, webFaviconPath, webStylesPath } from "./paths.ts";
import { fsRoutes } from "./routes/fs.ts";
import { workspaceRoutes } from "./routes/workspaces.ts";
import { sessionRoutes } from "./routes/sessions.ts";
import { providerRoutes } from "./routes/providers.ts";
import { settingRoutes } from "./routes/settings.ts";
import { mcpRoutes } from "./routes/mcp.ts";
import { connectionRoutes } from "./routes/connections.ts";
import { federationRoutes } from "./routes/federation.ts";
import { FederationClient } from "./federation.ts";
import { isLoopbackHost, jsonError, LOOPBACK_HOSTS } from "./routes/util.ts";
export { isLoopbackHost } from "./routes/util.ts";
import type { InitialData } from "@lumisca/web/types";

export interface AppOptions {
  /** Repository root (defaults to the current working directory). */
  repoRoot?: string;
  /** Address to bind (defaults to 127.0.0.1 — loopback only). Remote
   * hosting sets LUMISCA_HOST. Binding a non-loopback address without a
   * token is refused at startup (see validateHostConfig). */
  hostname?: string;
  /** Extra hostnames (without port) accepted by the Host guard, e.g. a
   * Tailscale hostname or LAN IP when hosting remotely. Loopback
   * hostnames are always accepted; DNS-rebinding protection stays intact
   * because the Host check still applies. */
  allowedHosts?: string[];
  /** When set, requests require this token (X-Lumisca-Token header, the
   * `token` query parameter for browser WebSockets, or `?token=` on the
   * page URL). In production mode the page itself is also
   * guarded, so the token is a real capability, not just a barrier for
   * casual local processes. Used by the desktop shell so only its own
   * spawned server instance answers. */
  token?: string;
  /** Mutable holder for this server's origin (http://host:port), filled
   * by startServer's onListen — the real port is only known after the
   * listener binds (port 0 = ephemeral). The federation client reads it
   * lazily for its self-guard. */
  selfOrigin?: { current: string };
  /** The federation client, injected by startServer so it can start the
   * peer event streams once the origin is known. */
  fed?: FederationClient;
}

/** Lazily built/loaded frontend assets (client bundle, css, favicon). */
class Assets {
  private appJs: string | null = null;
  private appJsPromise: Promise<string> | null = null;
  private css: string | null = null;
  private favicon: Uint8Array | null = null;

  constructor(
    private readonly repoRoot: string,
    private readonly cacheDir: string,
  ) {}

  /** Packaged builds (deno compile, no repository layout) serve the
   * prebuilt assets from a JSON manifest pointed to by LUMISCA_ASSETS_FILE
   * (generated by scripts/build-desktop-assets.ts). */
  private async embedded(
    name: "app.js" | "styles.css" | "favicon.svg",
  ): Promise<string | undefined> {
    const path = Deno.env.get("LUMISCA_ASSETS_FILE");
    if (!path) return undefined;
    try {
      const manifest = JSON.parse(await Deno.readTextFile(path)) as Record<
        string,
        string
      >;
      return manifest[name];
    } catch {
      return undefined;
    }
  }

  private hasWebSources(): boolean {
    try {
      return Deno.statSync(webClientEntry(this.repoRoot)).isFile;
    } catch {
      return false;
    }
  }

  /** Build once; concurrent first requests share the same build. */
  getAppJs(): Promise<string> {
    if (this.appJs !== null) return Promise.resolve(this.appJs);
    if (this.appJsPromise === null) {
      this.appJsPromise = this.buildAppJs().then(
        (js) => {
          this.appJs = js;
          return js;
        },
        (error) => {
          // A failed build must not poison the cache: the next request
          // retries (in dev, invalidate() also clears it).
          this.appJsPromise = null;
          throw error;
        },
      );
    }
    return this.appJsPromise;
  }

  private buildAppJs(): Promise<string> {
    return (async (): Promise<string> => {
      if (!this.hasWebSources()) {
        // Packaged build: serve the prebuilt bundle.
        const embedded = await this.embedded("app.js");
        if (embedded !== undefined) return embedded;
        throw new Error(
          "Frontend sources not found and no embedded assets " +
            "(set LUMISCA_ASSETS_FILE or run from the repository)",
        );
      }
      await Deno.mkdir(this.cacheDir, { recursive: true });
      const outfile = join(this.cacheDir, "app.js");
      await bundleClient({
        cwd: this.repoRoot,
        entry: webClientEntry(this.repoRoot),
        outfile,
      });
      return Deno.readTextFile(outfile);
    })();
  }

  async getCss(): Promise<string> {
    if (this.css === null) {
      if (this.hasWebSources()) {
        this.css = await Deno.readTextFile(webStylesPath(this.repoRoot));
      } else {
        const embedded = await this.embedded("styles.css");
        if (embedded === undefined) {
          throw new Error("styles.css not found and no embedded assets");
        }
        this.css = embedded;
      }
    }
    return this.css;
  }

  async getFavicon(): Promise<Uint8Array> {
    if (this.favicon === null) {
      if (this.hasWebSources()) {
        this.favicon = await Deno.readFile(webFaviconPath(this.repoRoot));
      } else {
        const embedded = await this.embedded("favicon.svg");
        if (embedded === undefined) {
          throw new Error("favicon.svg not found and no embedded assets");
        }
        this.favicon = new TextEncoder().encode(embedded);
      }
    }
    return this.favicon;
  }
}

/** Startup validation: a non-loopback bind without a token would expose
 * the agent (bash tool included) to anyone who can reach the address.
 * Returns an error message, or null when the configuration is safe. */
export function validateHostConfig(
  host: string,
  token: string | undefined,
): string | null {
  if (isLoopbackHost(host) || token) return null;
  return `binding to "${host}" without LUMISCA_TOKEN would expose the agent ` +
    "to the network; set LUMISCA_TOKEN or bind a loopback address";
}

function hostnameOf(host: string | undefined): string {
  if (!host) return "";
  try {
    return new URL(`http://${host}`).hostname.replace(/^\[|\]$/g, "");
  } catch {
    return "";
  }
}

/** Origins allowed to read cross-origin responses (the Tauri WebView). */
const ALLOWED_ORIGINS = new Set([
  "tauri://localhost",
  "http://tauri.localhost",
]);

function isAllowedOrigin(origin: string, host: string | undefined): boolean {
  if (ALLOWED_ORIGINS.has(origin)) return true;
  try {
    const expected = new URL(`http://${host}`);
    const actual = new URL(origin);
    if (actual.origin === expected.origin) return true;
    // `localhost` / `127.0.0.1` / `::1` are the same server but different
    // origins; allow those loopback spellings only when the port matches,
    // so a different local port can never pass the check (otherwise any
    // other local dev server could read the API cross-origin).
    return actual.protocol === expected.protocol &&
      actual.port === expected.port &&
      LOOPBACK_HOSTS.has(actual.hostname.replace(/^\[|\]$/g, "")) &&
      LOOPBACK_HOSTS.has(hostnameOf(host));
  } catch {
    return false;
  }
}

/** Cleanup hooks per app instance, reached via disposeServer. */
const appDisposers = new WeakMap<Hono, () => void>();
const serverDisposers = new WeakMap<
  Deno.HttpServer<Deno.NetAddr>,
  () => void
>();

function disposeApp(app: Hono): void {
  appDisposers.get(app)?.();
}

/** Create the HTTP + WebSocket application. */
export function createApp(core: LumiscaCore, options: AppOptions = {}): Hono {
  const app = new Hono();
  const repoRoot = options.repoRoot ?? Deno.cwd();
  const assets = new Assets(repoRoot, join(repoRoot, ".lumisca-cache"));

  // Federated peers (the server-side connection registry): the hub proxies
  // their workspaces/sessions and relays their events, tagged with the
  // peer id so the UI can route them to the right tabs. startServer injects
  // its own client (started once the real origin is known); direct
  // createApp usage gets a client with no self-guard.
  const fed = options.fed ??
    new FederationClient(
      () => core.getConnections(),
      () => options.selfOrigin?.current ?? "",
    );
  if (!options.fed) fed.start();

  // The server is local-only by default: refuse requests that do not target
  // a loopback host (blocks DNS rebinding and cross-origin browser access).
  // Remote hosting opens additional hostnames via allowedHosts; the Host
  // check still applies to them, so DNS rebinding stays blocked.
  const allowedHosts = new Set(
    (options.allowedHosts ?? []).map((h) => h.toLowerCase()),
  );
  app.use("*", async (c, next) => {
    const host = hostnameOf(c.req.header("host"));
    if (!isLoopbackHost(host) && !allowedHosts.has(host)) {
      return c.text(
        "Forbidden: host is not allowed (loopback or LUMISCA_ALLOWED_HOSTS)",
        403,
      );
    }
    await next();
  });

  // Optional bearer token: blocks arbitrary local processes (curl, other
  // apps) from driving the agent, and — for remote hosting — anyone without
  // the token from reaching the page itself. The token is accepted as
  // the X-Lumisca-Token header, the `token` query parameter (WebSocket
  // handshakes), or `?token=` on the page URL (the desktop shell opens the
  // page that way). Static assets stay public (they contain no secrets) so
  // the authenticated page can load them without a token query.
  if (options.token) {
    const publicPath = (path: string) =>
      path === "/assets/app.js" || path === "/styles.css" ||
      path === "/favicon.svg";
    app.use("*", async (c, next) => {
      if (!publicPath(c.req.path)) {
        const supplied = c.req.header("x-lumisca-token") ??
          c.req.query("token");
        if (supplied !== options.token) {
          return c.json(
            { error: "Unauthorized: missing or invalid token" },
            401,
          );
        }
      }
      await next();
    });
  }

  // Route handlers throw instead of catching: unify error responses here.
  app.onError((error, c) => {
    return jsonError(c, error);
  });

  // Unknown API paths answer JSON like every other error, not an empty body.
  app.notFound((c) => {
    if (c.req.path.startsWith("/api") || c.req.path === "/ws") {
      return c.json({ error: "Not found" }, 404);
    }
    return c.text("Not found", 404);
  });

  appDisposers.set(app, () => {
    fed.close();
  });

  // The desktop shell (Tauri WebView) calls the API from another origin.
  // Only same-origin and the Tauri WebView origins may read responses.
  const corsHandler = cors({
    origin: (origin, c) =>
      isAllowedOrigin(origin, c.req.header("host")) ? origin : undefined,
    allowHeaders: ["content-type", "x-lumisca-token"],
  });
  app.use("/api/*", corsHandler);
  app.use("/ws", corsHandler);

  // Browsers send an Origin on WebSocket handshakes; CORS does not apply to
  // WS, so without this check any website could open ws://127.0.0.1:<port>/ws
  // and read every agent event. Non-browser clients (no Origin) are allowed —
  // they are already gated by the loopback-only Host check above.
  app.use("/ws", async (c, next) => {
    const origin = c.req.header("origin");
    if (
      origin !== undefined && !isAllowedOrigin(origin, c.req.header("host"))
    ) {
      return c.text("Forbidden: cross-origin WebSocket", 403);
    }
    await next();
  });

  app.get("/api/health", (c) => c.json({ ok: true }));

  // --- HTML page ------------------------------------------------------------

  /** Theme preference from the core settings ("system" when unset/unknown).
   * The client resolves "system" via prefers-color-scheme; the server only
   * knows it, so the shell falls back to dark for the first paint. */
  const theme = (): ThemeSetting => {
    const stored = core.getSetting(THEME_KEY);
    return stored === "light"
      ? "light"
      : stored === "system"
      ? "system"
      : "dark";
  };

  /** Resolved theme for the shell's first paint (no client-side flash). */
  const resolvedTheme = (): "light" | "dark" =>
    theme() === "light" ? "light" : "dark";

  /** Initial data for the app bootstrap, served as the externalized
   * /assets/initial-data.js script (inline scripts are banned by the page
   * CSP). Fresh per request — the client re-reads the data on every load,
   * so it can never go stale relative to the server's state. */
  const initialData = (): InitialData => ({
    workspaces: core.listWorkspaces(),
    theme: theme(),
  });

  const renderPage = async (c: Context) => {
    const css = await assets.getCss();
    return new Response(
      renderHtmlDocument(css, resolvedTheme(), {
        // The page's own host, so the CSP can name the WebSocket endpoint
        // (the UI's event stream) even when the page is served remotely.
        pageHost: c.req.header("host"),
        token: options.token,
      }),
      { headers: { "content-type": "text/html; charset=utf-8" } },
    );
  };

  app.get("/", (c) => renderPage(c));

  app.get("/assets/initial-data.js", (c) => {
    // `<` is escaped so the JSON can never close the script tag.
    const safeData = JSON.stringify(initialData()).replace(/</g, "\\u003c");
    const tokenLine = options.token
      ? `\nwindow.__LUMISCA_TOKEN__ = ${JSON.stringify(options.token)};`
      : "";
    return c.body(`window.__INITIAL_DATA__ = ${safeData};${tokenLine}`, 200, {
      "content-type": "application/javascript; charset=utf-8",
    });
  });

  app.get("/assets/app.js", async (c) => {
    try {
      const js = await assets.getAppJs();
      return c.body(js, 200, {
        "content-type": "application/javascript; charset=utf-8",
      });
    } catch (error) {
      return c.text(
        `Client bundle build failed: ${errorMessage(error)}`,
        500,
      );
    }
  });

  app.get("/styles.css", async (c) => {
    try {
      const css = await assets.getCss();
      return c.body(css, 200, { "content-type": "text/css; charset=utf-8" });
    } catch (error) {
      return c.text(String(error), 500);
    }
  });

  app.get("/favicon.svg", async (c) => {
    try {
      const svg = await assets.getFavicon();
      return c.newResponse(svg.buffer as ArrayBuffer, 200, {
        "content-type": "image/svg+xml",
      });
    } catch {
      return c.text("not found", 404);
    }
  });

  // SPA fallback: any other page renders the app shell.
  app.get("*", (c, next) => {
    if (c.req.path.startsWith("/api") || c.req.path === "/ws") {
      return next();
    }
    // Unknown static assets (e.g. /favicon.ico) get a real 404 instead of
    // the HTML shell, so browsers and CDNs do not cache a wrong document.
    if (/\.\w+$/.test(c.req.path)) {
      return c.text("Not found", 404);
    }
    return renderPage(c);
  });

  // --- API routes (mounted after the SPA fallback so /api passes through) ----

  app.route("/api", fsRoutes());
  app.route("/api", workspaceRoutes(core));
  app.route("/api", mcpRoutes(core));
  app.route("/api", sessionRoutes(core));
  app.route("/api", providerRoutes(core));
  app.route("/api", settingRoutes(core));
  app.route("/api", connectionRoutes(core, () => fed.restart()));
  app.route("/api", federationRoutes(core, fed));

  // --- websocket event stream ------------------------------------------------

  const ws = upgradeWebSocket(() => {
    let unsubscribe: (() => void) | undefined;
    let unsubscribeFed: (() => void) | undefined;
    return {
      onOpen(_evt, ws) {
        unsubscribe = core.subscribe((event) => {
          // Every event carries the peer id ("" = this server) so the UI
          // routes it to the right session tab.
          ws.send(JSON.stringify({ peerId: "", ...event }));
        });
        // Federated peers' events, tagged with their id. The peer's own
        // `peerId` marker ("" on its side) is stripped first, so the tag
        // is always the id this hub knows.
        unsubscribeFed = fed.subscribe((peerId, event) => {
          const { peerId: _stale, ...rest } = event as Record<string, unknown>;
          ws.send(JSON.stringify({ peerId, ...rest }));
        });
      },
      onClose() {
        unsubscribe?.();
        unsubscribeFed?.();
      },
    };
  });

  app.get("/ws", ws);

  return app;
}

/** Start the server, bound to `options.hostname` (loopback by default). */
export function startServer(
  core: LumiscaCore,
  port = 8000,
  options?: AppOptions,
): Deno.HttpServer<Deno.NetAddr> {
  const hostname = options?.hostname ?? "127.0.0.1";
  // The hub's real origin is only known after binding (port 0 =
  // ephemeral); the federation self-guard reads it through this holder,
  // and the peer event streams start once it is known.
  const selfOrigin: { current: string } = { current: "" };
  const fed = new FederationClient(
    () => core.getConnections(),
    () => selfOrigin.current,
  );
  const app = createApp(core, { ...options, selfOrigin, fed });
  const server = Deno.serve(
    {
      hostname,
      port,
      onListen(addr) {
        selfOrigin.current = `http://${addr.hostname}:${addr.port}`;
        fed.start();
      },
    },
    app.fetch,
  );
  serverDisposers.set(server, () => disposeApp(app));
  return server;
}

/** Release resources tied to a running server (e.g. the dev watcher).
 * Call before server.shutdown() when shutting down gracefully. */
export function disposeServer(server: Deno.HttpServer<Deno.NetAddr>): void {
  serverDisposers.get(server)?.();
}
