import { join } from "node:path";
import { bundleClient } from "./bundle.ts";
import { webClientEntry, webFaviconPath, webStylesPath } from "./paths.ts";

/**
 * The frontend assets a server can serve: the bundled client, the styles,
 * and the favicon (binary assets base64-encoded so the manifest is text).
 * This module is the single owner of those assets — both the pre-build
 * script (scripts/build-desktop-assets.ts) and the runtime Assets class use
 * it, so the packaged and dev asset sources cannot drift.
 */

export interface AssetsManifest {
  "app.js": string;
  "styles.css": string;
  "favicon.png": string;
}

/** Bundle the client and read the static assets into a manifest. This is
 * the only producer of embedded assets; the runtime Assets class serves
 * either these or the repository sources. */
export async function buildAssetsManifest(
  repoRoot: string,
): Promise<{ manifest: AssetsManifest; appJsBytes: number }> {
  const tmp = join(
    Deno.env.get("TMPDIR") ?? Deno.env.get("TEMP") ?? "/tmp",
    `lumisca-app-${crypto.randomUUID()}.js`,
  );
  try {
    await bundleClient({
      cwd: repoRoot,
      entry: webClientEntry(repoRoot),
      outfile: tmp,
    });
    const appJs = await Deno.readTextFile(tmp);
    const css = await Deno.readTextFile(webStylesPath(repoRoot));
    const faviconBytes = await Deno.readFile(webFaviconPath(repoRoot));
    // Chunked so any icon size stays within the call-stack limits of
    // spread + String.fromCharCode.
    let faviconB64 = "";
    for (let i = 0; i < faviconBytes.length; i += 0x8000) {
      faviconB64 += btoa(
        String.fromCharCode(...faviconBytes.subarray(i, i + 0x8000)),
      );
    }
    return {
      manifest: {
        "app.js": appJs,
        "styles.css": css,
        "favicon.png": faviconB64,
      },
      appJsBytes: appJs.length,
    };
  } finally {
    await Deno.remove(tmp).catch(() => {});
  }
}

/** Load a prebuilt manifest from a JSON file (LUMISCA_ASSETS_FILE). */
export function readAssetsManifest(path: string): AssetsManifest {
  return JSON.parse(Deno.readTextFileSync(path)) as AssetsManifest;
}

/** Lazily built/loaded frontend assets (client bundle, css, favicon). */
export class Assets {
  // A single memoized promise: a resolved promise keeps returning the same
  // value, and a failed build nulls the slot so the next request retries.
  private appJsPromise: Promise<string> | null = null;
  private cssCache: string | null = null;
  private faviconCache: Uint8Array | null = null;

  constructor(
    private readonly repoRoot: string,
    private readonly cacheDir: string,
  ) {}

  /** Packaged builds (deno compile, no repository layout) serve the
   * prebuilt assets from a JSON manifest pointed to by LUMISCA_ASSETS_FILE
   * (generated by scripts/build-desktop-assets.ts). */
  private embedded(name: keyof AssetsManifest): string | undefined {
    const path = Deno.env.get("LUMISCA_ASSETS_FILE");
    if (!path) return undefined;
    try {
      return readAssetsManifest(path)[name];
    } catch {
      return undefined;
    }
  }

  private hasWebSources(): boolean {
    try {
      return Deno.statSync(webClientEntry(this.repoRoot)).isFile;
    } catch {
      return false;
    }
  }

  /** Build once; concurrent first requests share the same build. */
  getAppJs(): Promise<string> {
    if (this.appJsPromise === null) {
      this.appJsPromise = this.buildAppJs().catch((error) => {
        // A failed build must not poison the cache: the next request
        // retries (in dev, invalidate() also clears it).
        this.appJsPromise = null;
        throw error;
      });
    }
    return this.appJsPromise;
  }

  private buildAppJs(): Promise<string> {
    return (async (): Promise<string> => {
      if (!this.hasWebSources()) {
        // Packaged build: serve the prebuilt bundle.
        const embedded = this.embedded("app.js");
        if (embedded !== undefined) return embedded;
        throw new Error(
          "Frontend sources not found and no embedded assets " +
            "(set LUMISCA_ASSETS_FILE or run from the repository)",
        );
      }
      await Deno.mkdir(this.cacheDir, { recursive: true });
      const outfile = join(this.cacheDir, "app.js");
      await bundleClient({
        cwd: this.repoRoot,
        entry: webClientEntry(this.repoRoot),
        outfile,
      });
      return Deno.readTextFile(outfile);
    })();
  }

  async getCss(): Promise<string> {
    if (this.cssCache === null) {
      if (this.hasWebSources()) {
        this.cssCache = await Deno.readTextFile(webStylesPath(this.repoRoot));
      } else {
        const embedded = this.embedded("styles.css");
        if (embedded === undefined) {
          throw new Error("styles.css not found and no embedded assets");
        }
        this.cssCache = embedded;
      }
    }
    return this.cssCache;
  }

  async getFavicon(): Promise<Uint8Array> {
    if (this.faviconCache === null) {
      if (this.hasWebSources()) {
        this.faviconCache = await Deno.readFile(webFaviconPath(this.repoRoot));
      } else {
        const embedded = this.embedded("favicon.png");
        if (embedded === undefined) {
          throw new Error("favicon.png not found and no embedded assets");
        }
        // The packaged manifest stores binary assets as base64 text.
        this.faviconCache = Uint8Array.from(
          atob(embedded),
          (c) => c.charCodeAt(0),
        );
      }
    }
    return this.faviconCache;
  }
}
