/**
 * A mode message: a user prompt generated by an agent mode (e.g. review).
 * The UI renders it with a short text + mode badge instead of the full
 * prompt text. The full prompt — and any images attached to it — is sent
 * to the LLM via toLlmMessages.
 */
import type { ImageContent } from "../ai/types.ts";

/** Input data the client sends when a mode prompt is submitted. */
export interface ModePrompt {
  modeId: string;
  optionId: string;
  modeLabel: string;
  shortText: string;
}

/** A user message generated by an agent mode, stored in the transcript.
 * The UI shows `shortText` + `modeLabel` badge; the LLM sees `fullPrompt`
 * plus the attached images (converted by toLlmMessages). */
export interface ModeMessage {
  role: "mode";
  modeId: string;
  optionId: string;
  modeLabel: string;
  shortText: string;
  fullPrompt: string;
  /** Images the user attached in the composer, sent to the LLM after the
   * full prompt (the mode counterpart of a user message's image blocks;
   * empty when none were attached). The UI renders them in the bubble like
   * a user message's, and the rewind action restores them to the
   * composer. */
  images: ImageContent[];
  /** True when the mode prompt was delivered into the run that was already
   * active instead of starting its own run (see
   * SessionAgent.promptWhileRunning); absent when it started its own run.
   * The UI keeps such a prompt inside that run's turn instead of starting
   * a new one (see web's buildTurns) — the same delivery fact
   * NotificationMessage carries, with the same reason: a message that did
   * not start a run must not end the running turn. */
  steered?: boolean;
  timestamp: number;
}

/** Build a ModeMessage from a ModePrompt + full prompt text. `images` are
 * the composer attachments (`[]` when the user attached none). `steered`
 * marks a prompt delivered into the run that was already active; only the
 * delivery site (the session agent) knows that fact, so callers that
 * merely render or replay a mode prompt never set it. */
export function buildModeMessage(
  prompt: ModePrompt,
  fullPrompt: string,
  images: ImageContent[],
  timestamp: number,
  steered?: boolean,
): ModeMessage {
  return {
    role: "mode",
    modeId: prompt.modeId,
    optionId: prompt.optionId,
    modeLabel: prompt.modeLabel,
    shortText: prompt.shortText,
    fullPrompt,
    images,
    ...(steered === true ? { steered } : {}),
    timestamp,
  };
}

/** The agent-visible text of a mode message: the full prompt. Images
 * attached to the prompt are sent alongside it as content blocks of their
 * own (see toLlmMessages). */
export function modeFullPromptText(message: ModeMessage): string {
  return message.fullPrompt;
}
