/**
 * A mode message: a user prompt generated by an agent mode (e.g. review).
 * The UI renders it with a short text + mode badge instead of the full
 * prompt text. The full prompt is sent to the LLM via toLlmMessages.
 */

/** Input data the client sends when a mode prompt is submitted. */
export interface ModePrompt {
  modeId: string;
  optionId: string;
  modeLabel: string;
  shortText: string;
}

/** A user message generated by an agent mode, stored in the transcript.
 * The UI shows `shortText` + `modeLabel` badge; the LLM sees `fullPrompt`
 * (converted by toLlmMessages). */
export interface ModeMessage {
  role: "mode";
  modeId: string;
  optionId: string;
  modeLabel: string;
  shortText: string;
  fullPrompt: string;
  timestamp: number;
}

/** Build a ModeMessage from a ModePrompt + full prompt text. */
export function buildModeMessage(
  prompt: ModePrompt,
  fullPrompt: string,
  timestamp: number,
): ModeMessage {
  return {
    role: "mode",
    modeId: prompt.modeId,
    optionId: prompt.optionId,
    modeLabel: prompt.modeLabel,
    shortText: prompt.shortText,
    fullPrompt,
    timestamp,
  };
}

/** The agent-visible text of a mode message: the full prompt. */
export function modeFullPromptText(message: ModeMessage): string {
  return message.fullPrompt;
}